platform: linux

image_resource:
  type: docker-image
  source:
    repository: pcfkubo/kubo-ci

inputs:
  - name: git-cfcr-etcd-release
  - name: bbr-release
  - name: bbl-state

params:
  BOSH_DEPLOYMENT: bbr-etcd-single-node

run:
  path: git-cfcr-etcd-release/ci/scripts/run-bbr-tests.sh
