---
name: etcd

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

releases:
- name: cfcr-etcd
  version: latest
- name: bpm
  sha1: 5a03b988c725c6b5a1aed247c8c23c2bff9d421b
  url: https://bosh.io/d/github.com/cloudfoundry-incubator/bpm-release?v=0.4.0
  version: 0.4.0
- name: bosh-dns
  sha1: 9231b7c7d2f6aa85e0cb77fdeef7add54fdb3f1a
  url: https://bosh.io/d/github.com/cloudfoundry/bosh-dns-release?v=0.2.0
  version: 0.2.0

addons:
- name: bosh-dns
  include:
    stemcells:
    - os: ubuntu-trusty
  jobs:
  - name: bosh-dns
    release: bosh-dns
    properties:
      cache:
        enabled: true
      health:
        enabled: true
        server:
          tls: ((/dns_healthcheck_server_tls))
        client:
          tls: ((/dns_healthcheck_client_tls))
- name: bosh-dns-aliases
  jobs:
  - name: etcd-dns-aliases
    release: cfcr-etcd

instance_groups:
- name: etcd
  azs: [z1]
  instances: 1
  persistent_disk_type: 10GB
  vm_type: default
  stemcell: default
  networks:
  - name: default
  jobs:
  - name: etcd
    release: cfcr-etcd
    provides:
      etcd: {as: etcd}
    properties:
      tls:
        etcd:
          ca: ((tls_etcd.ca))
          certificate: ((tls_etcd.certificate))
          private_key: ((tls_etcd.private_key))
  - name: bpm
    release: bpm

- name: acceptance
  azs: [z1]
  instances: 1
  lifecycle: errand
  vm_type: default
  stemcell: default
  networks:
  - name: default
  jobs:
  - name: acceptance-tests
    release: cfcr-etcd
    consumes:
      etcd: {from: etcd}
  properties:
    tls:
      etcd_client:
        ca: ((tls_acceptance_etcd_client.ca))
        certificate: ((tls_acceptance_etcd_client.certificate))
        private_key: ((tls_acceptance_etcd_client.private_key))

update:
  serial: true
  canaries: 1
  max_in_flight: 1
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000

variables:
- name: /dns_healthcheck_tls_ca
  opsname: global_dns_healthcheck_tls_ca
  type: certificate
  options:
    is_ca: true
    common_name: dns-healthcheck-tls-ca

- name: /dns_healthcheck_server_tls
  opsname: global_dns_healthcheck_server_tls
  type: certificate
  options:
    ca: /dns_healthcheck_tls_ca
    common_name: health.bosh-dns
    extended_key_usage:
    - server_auth

- name: /dns_healthcheck_client_tls
  opsname: global_dns_healthcheck_client_tls
  type: certificate
  options:
    ca: /dns_healthcheck_tls_ca
    common_name: health.bosh-dns
    extended_key_usage:
    - client_auth

- name: etcd_ca
  type: certificate
  options:
    is_ca: true
    common_name: ca

- name: tls_etcd
  type: certificate
  options:
    ca: etcd_ca
    common_name: etcd.cfcr.internal
    alternative_names:
    - "etcd.cfcr.internal"
    - "*.etcd.cfcr.internal"
    extended_key_usage:
    - server_auth

- name: tls_acceptance_etcd_client
  type: certificate
  options:
    ca: etcd_ca
    common_name: etcd_acceptance_client
    extended_key_usage:
    - client_auth

features:
  use_dns_addresses: true
