---
name: etcd

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

releases:
- name: cfcr-etcd
  version: latest
- name: bpm
  version: "0.6.0"
  url: "https://bosh.io/d/github.com/cloudfoundry-incubator/bpm-release?v=0.6.0"
  sha1: "4f0f239abdc801d71de9063625aa56e3c42634b5"
- name: bosh-dns
  version: "1.6.0"
  url: "https://bosh.io/d/github.com/cloudfoundry/bosh-dns-release?v=1.6.0"
  sha1: "bb7f1cf29c4186fdba4a049fb6feb5638227d9a4"

addons:
- name: bosh-dns
  include:
    stemcells:
    - os: ubuntu-trusty
  jobs:
  - name: bosh-dns
    release: bosh-dns
    properties:
      cache:
        enabled: true
      health:
        enabled: true
        server:
          tls: ((/dns_healthcheck_server_tls))
        client:
          tls: ((/dns_healthcheck_client_tls))

instance_groups:
- name: etcd
  azs: [z1,z2,z3]
  instances: 3
  persistent_disk: 10240
  vm_type: default
  stemcell: default
  networks:
  - name: default
  jobs:
  - name: etcd
    release: cfcr-etcd
    provides:
      etcd: {as: etcd}
    properties:
      tls:
        etcd:
          ca: ((tls_etcd.ca))
          certificate: ((tls_etcd.certificate))
          private_key: ((tls_etcd.private_key))
        etcdctl:
          ca: ((tls_etcdctl.ca))
          certificate: ((tls_etcdctl.certificate))
          private_key: ((tls_etcdctl.private_key))
        peer:
          ca: ((tls_etcd_peer.ca))
          certificate: ((tls_etcd_peer.certificate))
          private_key: ((tls_etcd_peer.private_key))
  - name: bpm
    release: bpm

- name: acceptance
  azs: [z1]
  instances: 1
  lifecycle: errand
  vm_type: default
  stemcell: default
  networks:
  - name: default
  jobs:
  - name: acceptance-tests
    release: cfcr-etcd
    consumes:
      etcd: {from: etcd}
  properties:
    tls:
      etcd_client:
        ca: ((tls_etcdctl.ca))
        certificate: ((tls_etcdctl.certificate))
        private_key: ((tls_etcdctl.private_key))

update:
  serial: true
  canaries: 1
  max_in_flight: 1
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000

variables:
- name: /dns_healthcheck_tls_ca
  opsname: global_dns_healthcheck_tls_ca
  type: certificate
  options:
    is_ca: true
    common_name: dns-healthcheck-tls-ca

- name: /dns_healthcheck_server_tls
  opsname: global_dns_healthcheck_server_tls
  type: certificate
  options:
    ca: /dns_healthcheck_tls_ca
    common_name: health.bosh-dns
    extended_key_usage:
    - server_auth

- name: /dns_healthcheck_client_tls
  opsname: global_dns_healthcheck_client_tls
  type: certificate
  options:
    ca: /dns_healthcheck_tls_ca
    common_name: health.bosh-dns
    extended_key_usage:
    - client_auth

- name: etcd_ca
  type: certificate
  options:
    is_ca: true
    common_name: ca

- name: tls_etcd
  type: certificate
  options:
    ca: etcd_ca
    common_name: etcd.default.etcd.bosh
    alternative_names:
    - "etcd.default.etcd.bosh"
    - "*.etcd.default.etcd.bosh"
    extended_key_usage:
    - server_auth
    - client_auth

- name: tls_etcd_peer
  type: certificate
  options:
    ca: etcd_ca
    common_name: etcd.default.etcd.bosh
    alternative_names:
    - "etcd.default.etcd.bosh"
    - "*.etcd.default.etcd.bosh"
    extended_key_usage:
    - server_auth
    - client_auth

- name: tls_etcdctl
  type: certificate
  options:
    ca: etcd_ca
    common_name: etcd_acceptance_client
    extended_key_usage:
    - client_auth

features:
  use_dns_addresses: true
