required = ["github.com/onsi/ginkgo/ginkgo"]

[[constraint]]
  name = "github.com/coreos/etcd"
  version = "3.3.1"

[[constraint]]
  name = "github.com/onsi/ginkgo"
  version = "1.4.0"

[[constraint]]
  name = "github.com/onsi/gomega"
  version = "1.3.0"

[[constraint]]
  name = "github.com/satori/go.uuid"
  version = "1.2.0"

[[constraint]]
  revision = "f58b3a1827c1f4359397485d781c16f102e4b430"
  name = "github.com/cloudfoundry/bosh-cli"

[[override]]
  revision = "c1f48d5ce4f292dfb775ef52aaedd15be323510d"
  name = "github.com/cheggaaa/pb"

[[override]]
  revision = "a960ab178e64b43d19051be6fd2891ff695bb206"
  name = "github.com/cloudfoundry/bosh-utils"

[prune]
  go-tests = true
  non-go = true
  unused-packages = true
