---
- type: replace
  path: /name
  value: ((deployment-name))

- type: replace
  path: /variables/name=tls_etcd/options/common_name
  value: etcd.default.((deployment-name)).bosh

- type: replace
  path: /variables/name=tls_etcd/options/alternative_names
  value:
  - "etcd.default.((deployment-name)).bosh"
  - "*.etcd.default.((deployment-name)).bosh"

- type: replace
  path: /variables/name=tls_etcd_peer/options/common_name
  value: etcd.default.((deployment-name)).bosh

- type: replace
  path: /variables/name=tls_etcd_peer/options/alternative_names
  value:
  - "etcd.default.((deployment-name)).bosh"
  - "*.etcd.default.((deployment-name)).bosh"
